// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.DAL.ContextClasses;

#nullable disable

namespace Project.DAL.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20240626214535_mig123")]
    partial class mig123
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "e8d122b7-82ed-440f-a273-d885684bcee4",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4639f22b-5e50-4884-af9e-1faae216a2fa",
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 433, DateTimeKind.Utc).AddTicks(9074),
                            Email = "aost@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "AOST@GMAIL.COM",
                            NormalizedUserName = "AOST",
                            PasswordHash = "AQAAAAIAAYagAAAAEGDB7IDKdVvk5Gp7qbaeVOShRGK3lINf3gkBZ6RfMZQYxhe4Wa9pqvnQeao9scghoQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0055bde5-d414-4207-9ca6-d08be0958af2",
                            Status = 0,
                            TwoFactorEnabled = false,
                            UserName = "aost"
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserProfile", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Cast", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VideoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Casts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7336),
                            FirstName = "Christian",
                            LastName = "Bale",
                            Status = 0
                        },
                        new
                        {
                            ID = 2,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7341),
                            FirstName = "Christopher",
                            LastName = "Nolen",
                            Status = 0
                        },
                        new
                        {
                            ID = 3,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7342),
                            FirstName = "Heath",
                            LastName = "Ledger",
                            Status = 0
                        },
                        new
                        {
                            ID = 4,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7343),
                            FirstName = "Aaron",
                            LastName = "Eckhart",
                            Status = 0
                        },
                        new
                        {
                            ID = 5,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7344),
                            FirstName = "Michael",
                            LastName = "Caine",
                            Status = 0
                        },
                        new
                        {
                            ID = 6,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7345),
                            FirstName = "Morgon",
                            LastName = "Freeman",
                            Status = 0
                        },
                        new
                        {
                            ID = 7,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7346),
                            FirstName = "Cillian",
                            LastName = "Murphy",
                            Status = 0
                        },
                        new
                        {
                            ID = 8,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7347),
                            FirstName = "Justin",
                            LastName = "Theroux",
                            Status = 0
                        },
                        new
                        {
                            ID = 9,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7347),
                            FirstName = "Josh",
                            LastName = "Lucas",
                            Status = 0
                        },
                        new
                        {
                            ID = 10,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7349),
                            FirstName = "Reese",
                            LastName = "Witherspoon",
                            Status = 0
                        },
                        new
                        {
                            ID = 11,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7349),
                            FirstName = "Samantha",
                            LastName = "Mathis",
                            Status = 0
                        },
                        new
                        {
                            ID = 12,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7350),
                            FirstName = "Jared",
                            LastName = "Leto",
                            Status = 0
                        },
                        new
                        {
                            ID = 13,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7351),
                            FirstName = "Willem",
                            LastName = "Dafoe",
                            Status = 0
                        },
                        new
                        {
                            ID = 14,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7352),
                            FirstName = "Mary",
                            LastName = "Harron",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Genre", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7195),
                            GenreName = "Drama",
                            Status = 0
                        },
                        new
                        {
                            ID = 2,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7207),
                            GenreName = "Action",
                            Status = 0
                        },
                        new
                        {
                            ID = 3,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7208),
                            GenreName = "Adventure",
                            Status = 0
                        },
                        new
                        {
                            ID = 4,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7209),
                            GenreName = "Animation",
                            Status = 0
                        },
                        new
                        {
                            ID = 5,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7209),
                            GenreName = "Biography",
                            Status = 0
                        },
                        new
                        {
                            ID = 6,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7222),
                            GenreName = "Comedy",
                            Status = 0
                        },
                        new
                        {
                            ID = 7,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7223),
                            GenreName = "Crime",
                            Status = 0
                        },
                        new
                        {
                            ID = 8,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7223),
                            GenreName = "Documentary",
                            Status = 0
                        },
                        new
                        {
                            ID = 9,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7224),
                            GenreName = "Family",
                            Status = 0
                        },
                        new
                        {
                            ID = 10,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7226),
                            GenreName = "Fantasy",
                            Status = 0
                        },
                        new
                        {
                            ID = 11,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7226),
                            GenreName = "History",
                            Status = 0
                        },
                        new
                        {
                            ID = 12,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7227),
                            GenreName = "Horror",
                            Status = 0
                        },
                        new
                        {
                            ID = 13,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7228),
                            GenreName = "Mystery",
                            Status = 0
                        },
                        new
                        {
                            ID = 14,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7229),
                            GenreName = "Romance",
                            Status = 0
                        },
                        new
                        {
                            ID = 15,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7229),
                            GenreName = "War",
                            Status = 0
                        },
                        new
                        {
                            ID = 16,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7230),
                            GenreName = "Western",
                            Status = 0
                        },
                        new
                        {
                            ID = 17,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7231),
                            GenreName = "Sci-Fi",
                            Status = 0
                        },
                        new
                        {
                            ID = 18,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7232),
                            GenreName = "Sport",
                            Status = 0
                        },
                        new
                        {
                            ID = 19,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7233),
                            GenreName = "Thriller",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Movie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VideoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7294),
                            MovieName = "The Dark Knight",
                            Status = 0
                        },
                        new
                        {
                            ID = 2,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7298),
                            MovieName = "American Psycho",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.MovieCast", b =>
                {
                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int>("CastID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameInMovie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MovieID", "CastID");

                    b.HasIndex("CastID");

                    b.ToTable("MovieCasts");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            CastID = 1,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7490),
                            NameInMovie = "Bruce Wayne",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 1,
                            CastID = 2,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7495),
                            Status = 0
                        },
                        new
                        {
                            MovieID = 1,
                            CastID = 3,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7496),
                            NameInMovie = "Joker",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 1,
                            CastID = 4,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7497),
                            NameInMovie = "Harvey Dent",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 1,
                            CastID = 5,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7498),
                            NameInMovie = "Alfred",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 1,
                            CastID = 6,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7500),
                            NameInMovie = "Lucius Fox",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 1,
                            CastID = 7,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7501),
                            NameInMovie = "Scarecrow",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 2,
                            CastID = 1,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7502),
                            NameInMovie = "Patrick Bateman",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 2,
                            CastID = 8,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7502),
                            NameInMovie = "Timothy Bryce",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 2,
                            CastID = 9,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7504),
                            NameInMovie = "Craig McDermott",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 2,
                            CastID = 10,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7504),
                            NameInMovie = "Evelyn Williams",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 2,
                            CastID = 11,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7505),
                            NameInMovie = "Courtney Rawlinson",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 2,
                            CastID = 12,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7506),
                            NameInMovie = "Paul Allen",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 2,
                            CastID = 13,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7506),
                            NameInMovie = "Donald Kimball",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 2,
                            CastID = 14,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7507),
                            Status = 0
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.MovieGenre", b =>
                {
                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MovieID", "GenreID");

                    b.HasIndex("GenreID");

                    b.ToTable("MovieGenres");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            GenreID = 1,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7707),
                            Status = 0
                        },
                        new
                        {
                            MovieID = 1,
                            GenreID = 2,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7711),
                            Status = 0
                        },
                        new
                        {
                            MovieID = 1,
                            GenreID = 7,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7712),
                            Status = 0
                        },
                        new
                        {
                            MovieID = 2,
                            GenreID = 7,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7713),
                            Status = 0
                        },
                        new
                        {
                            MovieID = 2,
                            GenreID = 1,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7713),
                            Status = 0
                        },
                        new
                        {
                            MovieID = 2,
                            GenreID = 12,
                            CreatedDate = new DateTime(2024, 6, 26, 21, 45, 34, 491, DateTimeKind.Utc).AddTicks(7715),
                            Status = 0
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.MovieList", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MovieLists");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.MovieListJunction", b =>
                {
                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int>("MovieListID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MovieID", "MovieListID");

                    b.HasIndex("MovieListID");

                    b.ToTable("MovieListJunctions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserProfile", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", "AppUser")
                        .WithOne("Profile")
                        .HasForeignKey("Project.ENTITIES.Models.AppUserProfile", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.MovieCast", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.Cast", "Cast")
                        .WithMany("MovieCasts")
                        .HasForeignKey("CastID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.Movie", "Movie")
                        .WithMany("MovieCasts")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cast");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.MovieGenre", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.MovieList", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", "AppUser")
                        .WithOne("MovieList")
                        .HasForeignKey("Project.ENTITIES.Models.MovieList", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.MovieListJunction", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.Movie", "Movie")
                        .WithMany("MovieListJunctions")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.MovieList", "MovieList")
                        .WithMany("MovieListJunctions")
                        .HasForeignKey("MovieListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("MovieList");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUser", b =>
                {
                    b.Navigation("MovieList")
                        .IsRequired();

                    b.Navigation("Profile")
                        .IsRequired();
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Cast", b =>
                {
                    b.Navigation("MovieCasts");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Movie", b =>
                {
                    b.Navigation("MovieCasts");

                    b.Navigation("MovieGenres");

                    b.Navigation("MovieListJunctions");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.MovieList", b =>
                {
                    b.Navigation("MovieListJunctions");
                });
#pragma warning restore 612, 618
        }
    }
}
