// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.DAL.ContextClasses;

#nullable disable

namespace Project.DAL.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20240626221008_mig125")]
    partial class mig125
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "16784401-b163-45ee-b29e-3b0cbdf79538",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c9813233-ee9e-4c41-bcce-f2aa4701f6aa",
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 415, DateTimeKind.Utc).AddTicks(6775),
                            Email = "aost@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "AOST@GMAIL.COM",
                            NormalizedUserName = "AOST",
                            PasswordHash = "AQAAAAIAAYagAAAAEKoa+XC4p0PMttWGR2utnL4uTpBFcI/Jq4NjCBnXP67EaR14jN+L+9k1+YTL+gIc4Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4db9603c-8eac-4ee0-8c92-903409f65a3b",
                            Status = 0,
                            TwoFactorEnabled = false,
                            UserName = "aost"
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserProfile", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Cast", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VideoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Casts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4931),
                            FirstName = "Christian",
                            LastName = "Bale",
                            Status = 0
                        },
                        new
                        {
                            ID = 2,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4935),
                            FirstName = "Christopher",
                            LastName = "Nolen",
                            Status = 0
                        },
                        new
                        {
                            ID = 3,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4936),
                            FirstName = "Heath",
                            LastName = "Ledger",
                            Status = 0
                        },
                        new
                        {
                            ID = 4,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4937),
                            FirstName = "Aaron",
                            LastName = "Eckhart",
                            Status = 0
                        },
                        new
                        {
                            ID = 5,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4938),
                            FirstName = "Michael",
                            LastName = "Caine",
                            Status = 0
                        },
                        new
                        {
                            ID = 6,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4940),
                            FirstName = "Morgon",
                            LastName = "Freeman",
                            Status = 0
                        },
                        new
                        {
                            ID = 7,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4941),
                            FirstName = "Cillian",
                            LastName = "Murphy",
                            Status = 0
                        },
                        new
                        {
                            ID = 8,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4942),
                            FirstName = "Justin",
                            LastName = "Theroux",
                            Status = 0
                        },
                        new
                        {
                            ID = 9,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4942),
                            FirstName = "Josh",
                            LastName = "Lucas",
                            Status = 0
                        },
                        new
                        {
                            ID = 10,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4944),
                            FirstName = "Reese",
                            LastName = "Witherspoon",
                            Status = 0
                        },
                        new
                        {
                            ID = 11,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4945),
                            FirstName = "Samantha",
                            LastName = "Mathis",
                            Status = 0
                        },
                        new
                        {
                            ID = 12,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4946),
                            FirstName = "Jared",
                            LastName = "Leto",
                            Status = 0
                        },
                        new
                        {
                            ID = 13,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4947),
                            FirstName = "Willem",
                            LastName = "Dafoe",
                            Status = 0
                        },
                        new
                        {
                            ID = 14,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4947),
                            FirstName = "Mary",
                            LastName = "Harron",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Genre", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4789),
                            GenreName = "Drama",
                            Status = 0
                        },
                        new
                        {
                            ID = 2,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4797),
                            GenreName = "Action",
                            Status = 0
                        },
                        new
                        {
                            ID = 3,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4798),
                            GenreName = "Adventure",
                            Status = 0
                        },
                        new
                        {
                            ID = 4,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4798),
                            GenreName = "Animation",
                            Status = 0
                        },
                        new
                        {
                            ID = 5,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4799),
                            GenreName = "Biography",
                            Status = 0
                        },
                        new
                        {
                            ID = 6,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4813),
                            GenreName = "Comedy",
                            Status = 0
                        },
                        new
                        {
                            ID = 7,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4813),
                            GenreName = "Crime",
                            Status = 0
                        },
                        new
                        {
                            ID = 8,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4814),
                            GenreName = "Documentary",
                            Status = 0
                        },
                        new
                        {
                            ID = 9,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4815),
                            GenreName = "Family",
                            Status = 0
                        },
                        new
                        {
                            ID = 10,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4816),
                            GenreName = "Fantasy",
                            Status = 0
                        },
                        new
                        {
                            ID = 11,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4817),
                            GenreName = "History",
                            Status = 0
                        },
                        new
                        {
                            ID = 12,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4818),
                            GenreName = "Horror",
                            Status = 0
                        },
                        new
                        {
                            ID = 13,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4818),
                            GenreName = "Mystery",
                            Status = 0
                        },
                        new
                        {
                            ID = 14,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4819),
                            GenreName = "Romance",
                            Status = 0
                        },
                        new
                        {
                            ID = 15,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4820),
                            GenreName = "War",
                            Status = 0
                        },
                        new
                        {
                            ID = 16,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4820),
                            GenreName = "Western",
                            Status = 0
                        },
                        new
                        {
                            ID = 17,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4821),
                            GenreName = "Sci-Fi",
                            Status = 0
                        },
                        new
                        {
                            ID = 18,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4822),
                            GenreName = "Sport",
                            Status = 0
                        },
                        new
                        {
                            ID = 19,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4823),
                            GenreName = "Thriller",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Movie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VideoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4893),
                            MovieName = "The Dark Knight",
                            Status = 0
                        },
                        new
                        {
                            ID = 2,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(4897),
                            MovieName = "American Psycho",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.MovieCast", b =>
                {
                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int>("CastID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameInMovie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MovieID", "CastID");

                    b.HasIndex("CastID");

                    b.ToTable("MovieCasts");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            CastID = 1,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(5034),
                            NameInMovie = "Bruce Wayne",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 1,
                            CastID = 2,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(5039),
                            Status = 0
                        },
                        new
                        {
                            MovieID = 1,
                            CastID = 3,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(5040),
                            NameInMovie = "Joker",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 1,
                            CastID = 4,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(5041),
                            NameInMovie = "Harvey Dent",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 1,
                            CastID = 5,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(5042),
                            NameInMovie = "Alfred",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 1,
                            CastID = 6,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(5043),
                            NameInMovie = "Lucius Fox",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 1,
                            CastID = 7,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(5044),
                            NameInMovie = "Scarecrow",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 2,
                            CastID = 1,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(5045),
                            NameInMovie = "Patrick Bateman",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 2,
                            CastID = 8,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(5046),
                            NameInMovie = "Timothy Bryce",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 2,
                            CastID = 9,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(5047),
                            NameInMovie = "Craig McDermott",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 2,
                            CastID = 10,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(5048),
                            NameInMovie = "Evelyn Williams",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 2,
                            CastID = 11,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(5075),
                            NameInMovie = "Courtney Rawlinson",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 2,
                            CastID = 12,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(5076),
                            NameInMovie = "Paul Allen",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 2,
                            CastID = 13,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(5077),
                            NameInMovie = "Donald Kimball",
                            Status = 0
                        },
                        new
                        {
                            MovieID = 2,
                            CastID = 14,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(5078),
                            Status = 0
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.MovieGenre", b =>
                {
                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MovieID", "GenreID");

                    b.HasIndex("GenreID");

                    b.ToTable("MovieGenres");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            GenreID = 1,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(5140),
                            Status = 0
                        },
                        new
                        {
                            MovieID = 1,
                            GenreID = 2,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(5144),
                            Status = 0
                        },
                        new
                        {
                            MovieID = 1,
                            GenreID = 7,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(5145),
                            Status = 0
                        },
                        new
                        {
                            MovieID = 2,
                            GenreID = 7,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(5145),
                            Status = 0
                        },
                        new
                        {
                            MovieID = 2,
                            GenreID = 1,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(5146),
                            Status = 0
                        },
                        new
                        {
                            MovieID = 2,
                            GenreID = 12,
                            CreatedDate = new DateTime(2024, 6, 26, 22, 10, 7, 478, DateTimeKind.Utc).AddTicks(5147),
                            Status = 0
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.MovieList", b =>
                {
                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int>("AppUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MovieID", "AppUserID");

                    b.HasIndex("AppUserID");

                    b.ToTable("MovieLists");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserProfile", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", "AppUser")
                        .WithOne("Profile")
                        .HasForeignKey("Project.ENTITIES.Models.AppUserProfile", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.MovieCast", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.Cast", "Cast")
                        .WithMany("MovieCasts")
                        .HasForeignKey("CastID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.Movie", "Movie")
                        .WithMany("MovieCasts")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cast");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.MovieGenre", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.MovieList", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", "AppUser")
                        .WithMany("MovieLists")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.Movie", "Movie")
                        .WithMany("MovieLists")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUser", b =>
                {
                    b.Navigation("MovieLists");

                    b.Navigation("Profile")
                        .IsRequired();
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Cast", b =>
                {
                    b.Navigation("MovieCasts");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Movie", b =>
                {
                    b.Navigation("MovieCasts");

                    b.Navigation("MovieGenres");

                    b.Navigation("MovieLists");
                });
#pragma warning restore 612, 618
        }
    }
}
